name: Update submodule in draw.io
  
on:
  push:
    branches: 
      - main

jobs:
  update_parent_repos:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with: 
          repository: ${{ secrets.MONDRIAN_DRAWIO_REPOSITORY }}
          ref: dev_mondrian
          submodules: 'recursive'
          token: ${{ secrets.MONDRIAN_DRAWIO_TOKEN }}
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
